fix: Replace cglib with bytebuddy for Spock
There was a problem with cglib:
java.lang.NoClassDefFoundError: Could not initialize class org.spockframework.mock.runtime.CglibMockFactory$ConstructorFriendlyEnhancer.

This commit switches to bytebuddy which resolves the problem.